global:
  scrape_interval: 15s # Interval scraping target
  evaluation_interval: 15s # Interval evaluasi rule

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['10.0.201.1:9100']

  - job_name: 'snmp-exporter'
    static_configs:
      - targets:
          - 10.10.10.254
          - 10.0.102.1
    metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116
