services:
  traefik:
    image: docker.io/library/traefik:v2.11.0
    container_name: traefik-prod-1-server
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    # -- (Optional) When using Cloudflare as Cert Resolver
    # environment:
    #   - CF_DNS_API_TOKEN=your-cloudflare-api-token
    # -- (Optional) When using a custom network
    networks:
      - frontend_br
      - backend_br
    restart: unless-stopped

volumes:
  traefik-ssl-certs:
    driver: local

networks:
  frontend_br:
    external: true
  backend_br:
